Pin pip < 20.3
openstack-charmers/release-tools pull request #125
Opened 2020-12-03 13:13 UTC by AurelienLourot

Also removing from requirements.txt what was already in
test-requirements.txt

pip 20.3 just got released with a new default resolver
which turned out to be problematic. Also pip 21 will drop
support for python 3.5 soon anyway.

2020-12-03 13:15 UTC, AurelienLourot commented
Validating here: https://review.opendev.org/c/openstack/charm-ceph-radosgw/+/764641

2020-12-03 14:10 UTC, AurelienLourot commented
`tox` has now been upgraded on OSCI. Validating this change here: https://review.opendev.org/c/openstack/charm-ceph-radosgw/+/764641

2020-12-03 18:18 UTC, thedac requested changes
Can we add to tox.ini: minversion = 3.20.0.
So that when this fails for people, it is obvious why. Maybe we can add a link to internal documentation of https://paste.ubuntu.com/p/GhcsppQbJk/

2020-12-04 09:01 UTC, fnordahl approved these changes
LGTM, Davids concerns appear to be addressed.

2020-12-04 09:02 UTC, merged