Update global files for sunbeam charms
openstack-charmers/release-tools pull request #241
Opened 2022-07-22 06:43 UTC by hemanthnakkina

Create tox, requirements, test-requirements for sunbeam charms
Update scripts to handle new charm structure ops-unknown

2022-07-22 10:00 UTC, ajkavanagh requested changes
I think there is an opportunity to introduce an `upper-contraints.txt` file to the global config that lists the upper bounds of python modules, and then using the '-c' on 'pip' (and related friends) when installing modules/building charms.  See [here](https://pip.pypa.io/en/stable/user_guide/#constraints-files) for more details.

This is something I'd like to roll out across all the charms by the end of the dev cycle and this seems like a good place to start.

Also, we definitely want to re-pin pip to < 23 for this round; we pinned to <20.3 previously because towards the end of a dev cycle (and close to release), pip release 20.3.2 that broke everything as we don't have good dependencies sorted out.  However, there's a golden opportunity to resolve this at this stage in the cycle, so it might be useful to sort it now.

2022-07-25 10:18 UTC, hemanthnakkina commented on _update-tox-files
> +        esac
Done

2022-07-25 10:19 UTC, hemanthnakkina commented on global/README.md
> +3. Ops (Operator framework)
I am not sure about this and left with 3 types of charms for now. We can change names and add new type once the test framework is decided and new ops machine charms are created.

2022-07-25 10:21 UTC, hemanthnakkina commented on global/ops-unknown/tox.ini
> +  setuptools<50.0.0
For now, removed all pinning to see if everything works fine. As of now there are no issues (atleast with pep8, py3 tests). Can we update these constraints as and when we see issues?

2022-07-25 12:11 UTC, ajkavanagh commented on global/README.md
> +3. Ops (Operator framework)
We do already have at least one ops framework machine charm: https://github.com/openstack/charm-manila-netapp

So it definitely exists. I guess my question is "are they similar enough to be treated as one category, or should they be treated separately" from a tox, charmcraft, etc. perspective?

2022-07-27 07:24 UTC, gnuoy commented on global/README.md
> +3. Ops (Operator framework)
ceph-iscsi, ceph-dashboard, openstack-loadbalancer are all ops machine charms. At the moment the ops machine charms and the ops k8s charms are different categories. They use different libraries and have different structure.

2022-07-27 07:24 UTC, gnuoy commented on _update-tox-files
> +            ops-unknown)
I think we should fix whatever is generating the category name *ops-unknown* (it's probably the script `what-is`). I think we need ops-k8s and ops-machine or something similar

2023-07-20 17:00 UTC, ajkavanagh approved these changes

2023-07-20 17:01 UTC, merged