Pin charmcraft to 1.7/stable
openstack-charmers/release-tools pull request #243
Opened 2022-07-28 16:28 UTC by coreycb

Switch from 1.5/stable to 1.7/stable to get 22.04 support.

2022-07-29 13:46 UTC, wolsen approved these changes

2022-08-01 16:54 UTC, freyes requested changes
We will need to update zosci-config to use a different charmcraft version based on osci.yaml maybe(?), because at the moment we use 1.5 for all builds.

https://github.com/openstack-charmers/zosci-config/pull/190

2022-08-02 11:21 UTC, ajkavanagh commented
> We will need to update zosci-config to use a different charmcraft version based on osci.yaml maybe(?), because at the moment we use 1.5 for all builds.
> 
> [openstack-charmers/zosci-config#190](https://github.com/openstack-charmers/zosci-config/pull/190)

Yes, and somehow, just for master, rather than the stable branches; it would be ideal if zosci-config could use the version that release-tools uses.  However, this is only for the launchpad builders and thus, I'm a +1 on it to.

2022-08-02 11:22 UTC, merged

2022-08-02 11:41 UTC, ajkavanagh commented
See also: https://github.com/openstack-charmers/zosci-config/pull/218