Drop pinning from tox.ini and obsolete build-requirements.txt
openstack-charmers/release-tools pull request #275
Opened 2023-01-04 13:23 UTC by fnordahl

Please review commit by commit

2023-01-04 15:32 UTC, gnuoy requested changes

2023-01-04 16:35 UTC, fnordahl commented on global/classic-zaza/tox.ini
> +  pip install {opts} {packages}
:+1:

2023-01-04 17:51 UTC, fnordahl commented
The removal of `skip_sdist` did not work quite as intended, will revisit

2023-01-05 09:49 UTC, gnuoy commented
Tested with classic charm here: https://review.opendev.org/c/openstack/charm-openstack-dashboard/+/869221

2023-01-05 09:50 UTC, gnuoy approved these changes

2023-01-05 09:50 UTC, merged